# added for aws builds
# vars - https://docs.travis-ci.com/user/environment-variables/#convenience-variables
language: python
python:
  - '2.7'
branches:
  only: feature-init
install:
  - pip install awscli
  - pip install aws-sam-cli
script:
  - aws sts get-caller-identity | jq '.'
  - export AWS_DEFAULT_REGION=us-west-2
  - aws ssm get-parameter --name /travisci/contactless
  #- aws ssm get-parameter --name /travisci/contact/${TRAVIS_BRANCH}
  - echo $TRAVIS_BRANCH
  - echo $TRAVIS_PULL_REQUEST_BRANCH
  - export BUILD_BUCKET=sam-build-ci
  - export SAM_STACK_NAME=contactless-init
  - sam validate
  #- sam --region us-west-2 validate
  - sam package --template-file template.yaml --s3-bucket ${BUILD_BUCKET} --output-template-file interim-template.yaml
  - sam deploy  --template-file interim-template.yaml --stack-name ${SAM_STACK_NAME} --capabilities CAPABILITY_IAM
notifications:
  email:
    on_failure: always
