# added for aws builds
language: python
python:
  - '2.7'
branches:
  only: feature-init
install:
  - pip install awscli
  - pip install aws-sam-cli
script:
  - aws sts get-caller-identity
  - export AWS_DEFAULT_REGION=us-west-2
  - sam validate
  #- sam --region us-west-2 validate
  #- sam package --template-file template.yaml
notifications:
  email:
    on_failure: always
