# uses aws/codebuild/nodejs:8.11.0
#
version: 0.2


phases:

  install:
    commands:
      - npm install -g serverless
  build:
    commands:
  post_build:
    commands:
      - echo $AWS_REGION
      - SLS_DEBUG=* serverless deploy --stack $STACK_NAME --stage $STACK_NAME --region $AWS_REGION --verbose
      #- serverless deploy --stage dev --region $AWS_REGION
      - serverless info --region $AWS_REGION

artifacts:
  files:
    - serverless.yml
