AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Credit Text Outbound Service



Globals:
  Function:
    Runtime: python3.6
    # Environment:
    #   Variables:
    #     DB_MESSENGER: !Ref MessengerTable


Resources:
  ContactUsFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: handler.handle
      Runtime: python2.7
      CodeUri: src/

  # ApiGatewayApi:
  #   Type: AWS::Serverless::Api
  #   Properties:
  #     StageName: api
  #     DefinitionUri: swagger.yaml
