AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Credit Text Outbound Service



Globals:
  Function:
    Runtime: python3.6
    # Environment:
    #   Variables:
    #     DB_MESSENGER: !Ref MessengerTable
Parameters:

  DomainName:
    Type: String
    Default: mattcliff.net
    Description: DNS Domain Name (must have record in Route 53)

  CertificateArn:
    Type: String
    Default: arn:aws:acm:us-east-1:220065781146:certificate/99c23c6e-a2cf-4e83-ba1e-846f373e0d79
    Description: ARN for SSL certificate



Resources:
  ContactUsFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: handler.handle
      Runtime: python2.7
      CodeUri: src/

  # ApiGatewayApi:
  #   Type: AWS::Serverless::Api
  #   Properties:
  #     StageName: api
  #     DefinitionUri: swagger.yaml

  ApiGatewayDomain:
    Type: AWS::ApiGateway::DomainName
    Properties:
      DomainName: {"Fn::Join" : ["", [
        {"Ref": "AWS::StackName"}, "-api.",
        {"Ref": "DomainName"}
      ]]}
      CertificateArn: {"Ref": "CertificateArn"}
