AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Contact Service



Globals:
  Function:
    Runtime: python3.7
    # Environment:
    #   Variables:
    #     DB_MESSENGER: !Ref MessengerTable
Parameters:

  DomainName:
    Type: String
    Default: ""
    Description: DNS Domain Name (must have record in Route 53)

  CertificateArn:
    Type: String
    Default: ""
    Description: ARN for SSL certificate

  ApiName:
    Type: String
    Default: api
    Description: Hostname for the API



Resources:
  ContactUsFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: handler.handle
      CodeUri: src/
      Environment:
        Variables:
          API_URL: {"Fn::Join": ["", [ {"Ref" :"ApiName"}, ".", {"Ref" : "DomainName"}]]}
      Events:
        ContactUs:
          Type: Api
          Properties:
            Path: /
            Method: get


  # ApiGatewayApi:
  #   Type: AWS::Serverless::Api
  #   Properties:
  #     StageName: api
  #     DefinitionUri: swagger.yaml

  MyDNSRecord:
    Type: 'AWS::Route53::RecordSetGroup'
    DependsOn: ApiGatewayDomain
    Properties:
      HostedZoneName: {"Fn::Join" : ["", [
        {"Ref": "DomainName"}, "."
      ]]}

      RecordSets:
        - Type: A
          Name:  {"Fn::Join" : ["", [
            {"Ref": "ApiName"}, ".",
            {"Ref": "DomainName"}
          ]]}
          AliasTarget:
            HostedZoneId: Z2FDTNDATAQYW2   # hardcoded for all cloudfront
            DNSName: { "Fn::GetAtt" : ApiGatewayDomain.DistributionDomainName }



  ApiGatewayDomain:
    Type: AWS::ApiGateway::DomainName
    Properties:
      DomainName: {"Fn::Join" : ["", [
        {"Ref": "ApiName"}, ".",
        {"Ref": "DomainName"}
      ]]}
      CertificateArn: {"Ref": "CertificateArn"}


  ApiGatewayMapping:
    Type: AWS::ApiGateway::BasePathMapping
    DependsOn: ApiGatewayDomain
    Properties:
      DomainName: { "Ref" : ApiGatewayDomain }
      RestApiId: { "Ref" : ServerlessRestApi }
      Stage: Prod



Outputs:

  ApiURL:
    Description: API endpoint
    Value: {"Fn::Join": ["", [ {"Ref" :"ApiName"}, ".", {"Ref" : "DomainName"}]]}
